lr_finder:
  train_path: 'dataset/train.txt'
  val_path: 'dataset/val.txt'
  test_path: 'dataset/test.txt'
  batch_size: 32
  warmup_steps: 100
  epochs: 1
  lr: 1e-4
  accumulate_grad_batches: 1

SGD:
  train_path: 'dataset/train.txt'
  val_path: 'dataset/val.txt'
  test_path: 'dataset/test.txt'
  batch_size: 32
  epochs: 1
  lr: 1e-4
